#!/usr/bin/env python3
"""
Segment EMG recordings with a fixed timeline, export one CSV per exercise,
and save the exact segmentation metadata used for the run.

"""

import pandas as pd
import numpy as np
import argparse
import os
import re
from datetime import datetime

# ============================================================================
# MODIFY THIS SECTION FOR EACH PARTECIPANT
# ============================================================================


## === PARTECIPANT TIMELINE ===
# Timeline in seconds (relative to offset)
# Format: (exercise, set, start_sec, end_sec, note)
TIMELINE = [
    (1, 1, 6, 14, "ex1/set1"),
    (1, 2, 26, 35, "ex1/set2"),
    (2, 1, 47, 56, "ex2/set1"),
    (2, 2, 69, 78, "ex2/set2"),
    (3, 1, 86, 94, "ex3/set1"),
    (3, 2, 104, 111, "ex3/set2"),
    (4, 1, 122, 131, "ex4/set1"),
    (4, 2, 140, 151, "ex4/set2"),
    (5, 1, 158, 166, "ex5/set1"),
    (5, 2, 176, 185, "ex5/set2"),
    (6, 1, 191, 205, "ex6/set1"),
    (6, 2, 213, 230, "ex6/set2"),
    (7, 1, 236, 251, "ex7/set1"),
    (7, 2, 257, 270, "ex7/set2"),
    (8, 1, 283, 295, "ex8/set1"),
    (8, 2, 300, 312, "ex8/set2"),
]

RUN_INDEX = 20

## Offset from device activation to first useful data (in seconds)
DEVICE_START_OFFSET = 0  # Offset in seconds

## Automatic calculation: useful duration = max(end_sec) of the timeline (already relative to the offset)
TOTAL_DURATION_FROM_DEVICE = max([end for (_, _, _, end, _) in TIMELINE])

## Sampling frequency (Hz)
SAMPLING_FREQUENCY = 50 # Sampling frequency

# Use automatic movement detection (True) or use offset directly as timeline start (False)
# Set to False when you have exact timing from video and don't need automatic detection
USE_AUTOMATIC_DETECTION = False

## Notes about the timeline (optional, for documentation)
TIMELINE_NOTES = """
Partecipant H20 (Day5_H6):
- DEVICE_START_OFFSET = 0s (timeline from the start of the file)
- Timeline was refined after inspecting the full recording plot generated by
    Plot_full_time_temp.py, then adjusted with the timeline overlay plot from
    Plot_timeline_overlay.py to verify the final segmentation boundaries
- fs = 50 Hz
"""


# ============================================================================
# END OF CONFIGURATION - DO NOT MODIFY BELOW
# ============================================================================

def detect_first_movement(df, fs, threshold_multiplier=3.0):
    """
    Detect the first significant movement (first useful data).
    Returns sample index of first movement.
    """
    data = df.values
    
    # Use the first 5s as baseline
    baseline_samples = int(5 * fs)
    
    # Find first significant peak in any channel
    for ch in range(data.shape[1]):
        channel_data = data[:, ch]
        baseline = np.median(channel_data[:baseline_samples])
        
        # Find the first peak above the threshold
        for i in range(baseline_samples, len(channel_data)):
            if channel_data[i] > baseline * threshold_multiplier:
                print(f"  Detected first movement at sample {i} ({i/fs:.1f}s) in Channel_{ch+1}")
                return i
    
    return baseline_samples  # fallback


def segment_with_timeline(df, fs, first_movement_idx, output_dir, input_stem):
    """
    Segment using absolute timeline starting from first useful movement.
    """
    os.makedirs(output_dir, exist_ok=True)
    
    exercises = {}
    timeline_records = []
    
    print(f"\nSegmenting with timeline (relative to first movement at sample {first_movement_idx}):")
    
    for ex_num, set_num, start_sec, end_sec, note in TIMELINE:
        if ex_num not in exercises:
            exercises[ex_num] = []
        
        # Convert timeline seconds to absolute sample indices
        start_sample = first_movement_idx + int(start_sec * fs)
        end_sample = first_movement_idx + int(end_sec * fs)
        
        # Ensure we don't go beyond data bounds
        start_sample = max(0, start_sample)
        end_sample = min(len(df), end_sample)
        
        # Extract segment
        segment_df = df.iloc[start_sample:end_sample].copy()
        
        exercises[ex_num].append({
            'set': set_num,
            'start_sec_rel': start_sec,
            'end_sec_rel': end_sec,
            'start_sec_abs': start_sample / fs,
            'end_sec_abs': end_sample / fs,
            'start_sample_abs': start_sample,
            'end_sample_abs': end_sample,
            'samples': len(segment_df),
            'duration_sec': end_sec - start_sec,
            'note': note,
            'data': segment_df
        })
        
        timeline_records.append({
            'exercise': ex_num,
            'set': set_num,
            'start_sec_relative': start_sec,
            'end_sec_relative': end_sec,
            'start_sec_absolute': start_sample / fs,
            'end_sec_absolute': end_sample / fs,
            'start_sample_absolute': start_sample,
            'end_sample_absolute': end_sample,
            'duration_sec': end_sec - start_sec,
            'samples': end_sample - start_sample,
            'note': note
        })
        
        print(f"  Ex{ex_num}/Set{set_num}: {start_sec}-{end_sec}s (rel), "
              f"{start_sample/fs:.1f}-{end_sample/fs:.1f}s (abs), {len(segment_df)} samples")
    
    # Save one file per exercise
    summary = []
    for ex_num in sorted(exercises.keys()):
        sets = exercises[ex_num]
        
        # Combine both sets
        all_data = pd.concat([s['data'] for s in sets], ignore_index=True)
        
        # Save the exercise file
        ex_file = os.path.join(output_dir, f"{input_stem}_ex{ex_num:02d}.csv")
        all_data.to_csv(ex_file, index=False)
        
        total_duration = sum(s['duration_sec'] for s in sets)
        print(f"Saved exercise {ex_num}: {ex_file}")
        print(f"  Sets: {len(sets)}, Total samples: {len(all_data)}, Duration: {total_duration:.2f}s")
        for s in sets:
            print(f"    Set {s['set']}: {s['start_sec_rel']}-{s['end_sec_rel']}s (rel), "
                  f"{s['start_sec_abs']:.1f}-{s['end_sec_abs']:.1f}s (abs), {s['samples']} samples - {s['note']}")
        
        summary.append({
            'exercise': ex_num,
            'sets': len(sets),
            'total_samples': len(all_data),
            'total_duration_sec': total_duration
        })
    
    # Save the timeline
    timeline_df = pd.DataFrame(timeline_records)
    timeline_file = os.path.join(output_dir, f"{input_stem}_timeline.csv")
    timeline_df.to_csv(timeline_file, index=False)
    print(f"Saved timeline: {timeline_file}")
    
    # Save summary
    summary_df = pd.DataFrame(summary)
    summary_file = os.path.join(output_dir, f"{input_stem}_exercises_summary.csv")
    summary_df.to_csv(summary_file, index=False)
    print(f"Saved summary: {summary_file}")
    
    # Save processing info
    info_file = os.path.join(output_dir, f"{input_stem}_processing_info.txt")
    with open(info_file, 'w') as f:
        f.write(f"Processing date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Sampling frequency: {fs:.2f} Hz\n")
        f.write(f"First movement sample: {first_movement_idx} ({first_movement_idx/fs:.2f}s)\n")
        f.write(f"Total duration: {TOTAL_DURATION_FROM_DEVICE}s\n")
        f.write(f"Device start offset: {DEVICE_START_OFFSET}s\n")
        f.write(f"Total exercises: {len(exercises)}\n")
        f.write(f"Total sets: {sum(len(sets) for sets in exercises.values())}\n")
        if TIMELINE_NOTES.strip():
            f.write(f"\nNotes:\n{TIMELINE_NOTES}")
    print(f"Saved processing info: {info_file}")


def save_config_file(config_root, input_stem, fs, offset_seconds, config_label=None):
    """
    Save the timeline and run configuration used for segmentation.
    """
    os.makedirs(config_root, exist_ok=True)
    if config_label:
        h_label = config_label
    else:
        h_match = re.search(r"_H(\d+)$", input_stem)
        h_label = f"H{h_match.group(1)}" if h_match else input_stem
    config_file = os.path.join(config_root, f"{h_label}_config.txt")

    with open(config_file, 'w') as f:
        f.write("Timeline Segmentation Config\n")
        f.write("=" * 40 + "\n")
        f.write(f"Input file: {input_stem}.csv\n")
        f.write(f"Sampling frequency: {fs:.2f} Hz\n")
        f.write(f"Offset seconds: {offset_seconds}\n")
        f.write(f"Total timeline rows: {len(TIMELINE)}\n\n")
        f.write("TIMELINE (exercise, set, start_sec, end_sec, note):\n")

        for ex_num, set_num, start_sec, end_sec, note in TIMELINE:
            f.write(f"({ex_num}, {set_num}, {start_sec}, {end_sec}, \"{note}\")\n")

        f.write("\nNotes:\n")
        f.write(TIMELINE_NOTES.strip() + "\n")

    print(f"Saved config file: {config_file}")


def main():
    parser = argparse.ArgumentParser(description='Segment EMG data by timeline')
    parser.add_argument('--input', required=True, help='Input CSV file')
    parser.add_argument('--fs', type=float, default=SAMPLING_FREQUENCY, 
                       help=f'Sampling frequency in Hz (default: {SAMPLING_FREQUENCY} Hz)')
    parser.add_argument('--total_duration', type=float, default=TOTAL_DURATION_FROM_DEVICE, 
                       help=f'Total duration from device activation to end of video (default: {TOTAL_DURATION_FROM_DEVICE}s)')
    parser.add_argument('--offset', type=float, default=DEVICE_START_OFFSET,
                       help=f'Offset from device activation to first useful data (default: {DEVICE_START_OFFSET}s)')
    parser.add_argument('--config-label', default=None,
                       help='Config filename label (example: H3 -> H3_config.txt)')
    args = parser.parse_args()
    
    fs = args.fs
    
    # Load data
    print(f"Loading: {args.input}")
    df = pd.read_csv(args.input)
    print(f"  Total samples in file: {len(df)}")
    print(f"  Channels: {len(df.columns)}")
    print(f"  Sampling frequency (fixed): {fs:.2f} Hz")
    
    # Keep only EMG columns
    cols = [c for c in df.columns if c.startswith('Channel_')]
    
    # Apply the offset to the data: discard the first offset_sample samples (as in the overlay)
    offset_sample = int(args.offset * fs)
    df_offset = df[cols].iloc[offset_sample:].reset_index(drop=True)

    print(f"\nData after offset: {len(df_offset)} samples, applied offset: {args.offset}s ({offset_sample} samples)")
    print(f"  Timeline starts at 0s = {args.offset}s of acquisition")

    # The timeline is already relative to this new zero
    # Segment relative to df_offset, starting from first_movement_idx = 0
    first_movement_idx = 0

    # Create output directories
    input_stem = os.path.splitext(os.path.basename(args.input))[0]
    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_root = os.path.join(script_dir, 'data')
    output_root = os.path.join(data_root, 'Segment_H')
    output_dir = os.path.join(output_root, f"{RUN_INDEX}_{input_stem}_timeline")
    config_root = os.path.join(data_root, 'config_timeline_H')
    print(f"\nOutput directory: {output_dir}")

    # Segment using the timeline (relative to post-offset data)
    segment_with_timeline(df_offset, fs, first_movement_idx, output_dir, input_stem)

    # Save config with timeline and run parameters
    save_config_file(config_root, input_stem, fs, args.offset, args.config_label)

    print(f"\n✓ Done! Output in: {output_dir}")


if __name__ == "__main__":
    main()
